#
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v. 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0,
# or the Eclipse Distribution License v. 1.0 which is available at
# http://www.eclipse.org/org/documents/edl-v10.php.
#
# SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause
#

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      actions-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "com.oracle.database.jdbc:*"
        versions: [ ">23.3.0.23.09" ]
      - dependency-name: "com.oracle.database.messaging:*"
        versions: [ ">23.3.1.0" ]
      # handle by hand, see also https://github.com/eclipse-ee4j/ee4j/issues/116
      - dependency-name: "org.eclipse.ee4j::*"
        versions: [ ">1.3.3" ]
      # corba tests need 1.3.3 (?)
      - dependency-name: "jakarta.transaction:*"
        versions: [ ">1.3.3" ]
      # test locally first before updating
      - dependency-name: "org.wildfly:*"
        versions: [ ">27.0.0.Final" ]
      # have multiple versions for running tests
      - dependency-name: "org.apache.derby:*"
        versions: [ ">10.16.1.1" ]
      # newer breaks tests
      - dependency-name: "org.jgroups:*"
        versions: [ ">5.3.11.Final" ]
      # required by pax-exam (?)
      - dependency-name: "jakarta.inject:jakarta.inject-api"
        versions: [ ">1.0" ]
    groups:
      maven-plugins:
        patterns:
          - "*:*-plugin"
      dependencies:
        patterns:
          - "*"
